// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 17 Mar 2020 22:39:14 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "binaryen/src/binaryen-c.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

